### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by mephiii** [vieira/homebridge-yeelight-wifi#11]
Hello,

first of all thanks for the great work. But i was really struggling to make it work.

My system:
- Raspberry Pi 3 B+
- Node JS 7.9.0
- NPM 5.6.0
- Homebridge 0.4.38

In this project i got several syntax error with unexpected token:

`[2018-4-1 19:29:26] /usr/local/lib/node_modules/homebridge-yeelight-wifi/index.js:15
);
 ^
SyntaxError: Unexpected token )`

`[2018-4-1 19:31:01] /usr/local/lib/node_modules/homebridge-yeelight-wifi/platform.js:56
    );
    ^
SyntaxError: Unexpected token )`

`[2018-4-1 19:31:35] /usr/local/lib/node_modules/homebridge-yeelight-wifi/platform.js:84
  ) {
  ^
SyntaxError: Unexpected token )`

`[2018-4-1 19:32:01] /usr/local/lib/node_modules/homebridge-yeelight-wifi/platform.js:97
      );
      ^
SyntaxError: Unexpected token )`

`[2018-4-1 19:32:36] /usr/local/lib/node_modules/homebridge-yeelight-wifi/utils.js:42
      );
      ^
SyntaxError: Unexpected token )`

In all cases the problem was a syntax error with a comma. After fixing that i got the following error:

`[2018-4-1 19:10:14] [homebridge-yeelight.yeelight] doing a round of proactive search for known devices.`
`/usr/local/lib/node_modules/homebridge-yeelight-wifi/platform.js:24`
`      const mcastInterface = config.multicast && config.multicast.interface;`
`                                   ^`
`TypeError: Cannot read property 'multicast' of null`

Since the main issue in the last error is regarding the multicast and the development there is ongoing i switched to version 1.0.2. After switching to the older version and fixing the syntax errors again it is working pretty well!

I am wondering that the project has so many downloads and i am the first one who issued the syntax errors? Anyway, i just want to understand why it is working for all others and i am getting the syntax errors.

Best regards

**Comment by vieira** [comment]
Hello @mephiii,

Thanks for reporting this, I will give it a look and let you know!

**Comment by vieira** [comment]
Hello @mephiii,

#13 should fix this issue. I just released 1.0.5 which contains the fix.

The issue only happens if you are using homebridge with no configuration file at all. While this plugin does not require any configuration file (although some settings can optionally be configured, like the duration of the transitions), I imagine most users are also using other plugins, most of which require a configuration file to exist, so they are not seeing this issue.

The issue was introduced by #5, five days ago.

Thanks for reporting!
