### ISSUE TITLE
Yeelight Color Default State

### ISSUE THREAD

**Issue by Hopflnger** [vieira/homebridge-yeelight-wifi#12]
Would it be possible to implement a "default state" which will be standard after switching off and on?
If I set a colour it is not possible to get the default state back, without powering off with the wall switch.

**Comment by daVid0n** [comment]
that is exactly what I am missing in first place -> how to get back to the default color, once another color was set? 

Further homekit keeps posting "info rgb is unsupported in Homekit, ignoring." everytime a color is sent, but it works perfectly, so why does it keep telling this?

I am currently on two colored Yeelights V2 and using the standard light reset function from the app by turning off and back on, but it would be nice to also have this same option directly in homekit, though I don't know if this is possible.

**Comment by vieira** [comment]
Hello,

As far as I know, Homekit has no mechanism to set a default color, but you can do it in the yeelight app by either manually picking a default color/brightness or by setting the lamp to remember its last state.
I imagine this is the kind of setting you only need (re)configure rarely?

The home app also allows you to save any current color by long pressing to replace one of the preset ones, so you can save the "default", change color and then go back to the "default".

@daVid0n: about the rgb message, that was caused by a firmware update. I set the color using HSV (the format used by homekit) but the lamp reports back the new color both in HSV and RGB. We use the HSV value and ignore the RGB. I will release an update soon and it will not show thar warning anymore.
