### ISSUE TITLE
Changed colors after firmware upgrade

### ISSUE THREAD

**Issue by cgeist** [vieira/homebridge-yeelight-wifi#27]
After the latest firmware upgrade of the yeelight bulbs (1.4.2_0066) all colors seem to be off by quite an bit. Can anyone help?

**Comment by niccolospa** [comment]
I’m noticing the same behavior, all colors seem different and less brighter than colors set by the Yeelight app. Is this a known issue?

**Comment by matkappert** [comment]
I would also like a fix for this.

**Comment by vieira** [comment]
This issue was caused by a Yeelight firmware update, multiple reports [here](https://forum.yeelight.com/t/topic/7393) and affects the bulb when in color mode (e.g. `set_hsv`). Brightness increases only to about 50% and from 50% to 100% no visible change in brightness can be seen. This is happening at the firmware level and has nothing to do with homekit or with the official app specifically.

The problem does not occur when the bulb is in color temperature mode. If a color temperature is set using `set_ct_abx`, brightness does increase correctly, however only tones of orange to bright white are supported (~1700 to 6500K).

Unfortunately, Homekit does not support light bulbs that expose both color and color temperature: 

> 8.107 Color Temperature: 
> (...)
> If this characteristic is included in the Lightbulb (page 217), Hue (page 151) and Saturation (page 159) must not be included as optional characteristics in Lightbulb (page 217).
> This characteristic must not be used for lamps which support color.

When a lamp supports color, Homekit sends the color temperature in terms of hue and saturation, that we can set using the yeelight `set_hsv` method, which has the brightness problem discussed above since the firmware update.

To sum up, this is something that used to work without problems, was broken by Yeelight in a firmware update (likely 1.4.2_0069) and should be fixed by them.

If brightness is more important than colors, I will release a new version where you can change your configuration to blacklist color. In that case we will expose color temperature (if supported) and use the `set_ct_abx` method which does not have the brightness limitation.

```json
        "defaultValue": {
            "aed78s": {
                "name": "Kitchen",
                "blacklist": ["set_hsv"]
            }
        }
```

**Comment by BTexier** [comment]
Since I use iOS 13 public beta, the Color is now working properly
