### ISSUE TITLE
GitHub Actions and repo ownership

### ISSUE THREAD

**Issue by okonet** [vieira/homebridge-yeelight-wifi#60]
@vieira can you please check why actions aren't working on this repo or give me admin rights to this repo so I can check? Alternatively, if you want, you can change the ownership of the repo and move it to me if you don't have time at the moment.

**Comment by vieira** [comment]
Hello @okonet,

Should be fixed now, changing from monthly to yearly billing and then back again seems to have solved the issue? Can you confirm?

I have tried giving you admin permissions but I don't see such an option, maybe because the repository is under my personal account and not some organization.

I don't have much free time these days, so if the repo being under my personal account is an obstacle for you, I have no problem transfering it.

**Comment by okonet** [comment]
I've checked with my repo and indeed it seems it is not possible to give admin rights to collaborators unless it's an org. I honestly don't want to get one more repo to maintain myself and I can always release under a separate name if needed. Let's try actions and automative releases (I hate doing manual releases) and see if that will work. I'd still appreciate your feedback when you have time so I'd keep it here as long as possible :)

**Comment by okonet** [comment]
Okay finally after ~20 empty commits I've managed to release a version automatically. Let's try keeping things like this. 

@vieira it's important for you to read the contributing.md to understand the release process (convention + squash & merge, basically).

Good thing is that we now have changelogs.
