### ISSUE TITLE
Yeelight Bulbs Getting Ungrouped

### ISSUE THREAD

**Issue by sabaatworld** [vieira/homebridge-yeelight-wifi#94]
I'm trying to group together 3 light bulbs, but one of them moves out of the group every time Homebridge restarts. Any ideas why this might be happening?

**Comment by vieira** [comment]
Hello @sabaatworld,

I am not sure but I think this might be caused by some new "default name" being generated when that happens and HomeKit looking at it as a different bulb.

You can try to set some static names for your bulbs (at least the ones you want to group) by setting it in the configuration file, see #76 for an example.
